"""Export Flow Studio's validated last-success portfolio artifacts for static hosting."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from flow_studio.homepage_artifacts import validate_artifact  # noqa: E402


def load_artifacts(source: Path) -> dict[str, dict]:
    artifacts: dict[str, dict] = {}
    for path in sorted(source.glob("portfolio-*.json")):
        skill = path.stem
        payload = json.loads(path.read_text(encoding="utf-8"))
        artifacts[skill] = validate_artifact(payload, skill)
    return artifacts


def javascript_snapshot(artifacts: dict[str, dict]) -> str:
    payload = {
        "schemaVersion": 1,
        "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "artifacts": artifacts,
    }
    encoded = json.dumps(payload, ensure_ascii=False, indent=2)
    encoded = encoded.replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return (
        "/* Generated by scripts/export_portfolio.py. Do not hand-edit portfolio content here. */\n"
        f"window.PORTFOLIO_SNAPSHOT = Object.freeze({encoded});\n"
    )


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    temp = Path(name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp, path)
    finally:
        temp.unlink(missing_ok=True)


def main() -> None:
    default_portfolio = Path(os.environ.get(
        "PORTFOLIO_DIR", Path.home() / ".zcode/workspace/default/portfolio"))
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "artifact_dir", nargs="?", type=Path,
        default=ROOT / "data/homepage_artifacts",
        help="Flow Studio homepage_artifacts directory",
    )
    parser.add_argument(
        "--output", type=Path,
        default=default_portfolio / "content-snapshot.js",
        help="Generated browser snapshot",
    )
    args = parser.parse_args()
    artifacts = load_artifacts(args.artifact_dir)
    if not artifacts:
        raise SystemExit(f"No valid portfolio artifacts found in {args.artifact_dir}")
    atomic_write(args.output, javascript_snapshot(artifacts))
    print(f"Exported {len(artifacts)} validated artifacts to {args.output}")


if __name__ == "__main__":
    main()
